# Generated by Django 2.2.6 on 2019-11-02 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BlogStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BlogToMetaTagMappingStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BlogToParagraphMappingStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTagStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTagType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('paragraph_id', models.AutoField(primary_key=True, serialize=False)),
                ('paragraph_body', models.CharField(max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphToMediaMappingStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ParaGraphToMediaMaping',
            fields=[
                ('paragraph_to_media_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('media_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media_management.Media')),
                ('paragraph_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Paragraph')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.ParagraphStatus'),
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.MetaTagStatus')),
                ('type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.MetaTagType')),
            ],
        ),
        migrations.CreateModel(
            name='BlogToParagraphMapping',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('blog_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('paragraph_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Paragraph')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogToParagraphMappingStatus')),
            ],
        ),
        migrations.CreateModel(
            name='BlogToMetaTagMapping',
            fields=[
                ('blog_to_meta_tag_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('blog_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogToMetaTagMappingStatus')),
                ('tag_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.MetaTag')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogStatus'),
        ),
    ]
