# Generated by Django 2.2.6 on 2019-11-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParaGraphToMediaMaping',
            new_name='ParagraphToMediaMapping',
        ),
    ]
