# Generated by Django 2.2.6 on 2019-11-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_paragraphtomediamapping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph_body',
            field=models.TextField(blank=True, default=None),
        ),
    ]
