# Generated by Django 2.2.6 on 2019-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20191105_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatagtype',
            name='type_name_value',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
