# Generated by Django 2.2.6 on 2019-11-20 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOUserStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BOUser',
            fields=[
                ('bo_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('added_by', models.IntegerField()),
                ('added_date', models.DateField(default=datetime.datetime.now)),
                ('last_modified_by', models.IntegerField()),
                ('last_modified_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice_users.BOUserStatus')),
            ],
        ),
    ]
