# Generated by Django 2.2.6 on 2019-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouser',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='bouser',
            name='added_by',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
