# Generated by Django 2.2.6 on 2019-11-02 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default='not defined', max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(default='image', max_length=50)),
                ('file_content', models.FileField(upload_to='')),
                ('file_caption', models.CharField(blank=True, default=None, max_length=100)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media_management.MediaStatus')),
            ],
        ),
    ]
